### ISSUE TITLE
Broadcast problem

### ISSUE THREAD

**Issue by xEllesi** [Moshulika/Simple-Advertising#1]
Hi there, so i put yur plugin today, i really like it but when i try to do /broadcast it doesnt work, i think its a problem with essentials, 
can u do someting? like disable the prefix or something, thanks

**Comment by Moshulika** [comment]
Do you have an error? Also, what spigot version are you running?

**Comment by xEllesi** [comment]
No error, lastest version, 1.16.5

**Comment by Moshulika** [comment]
Okay, I'll be working on a fix today

**Comment by xEllesi** [comment]
thanks a lot <3

**Comment by Moshulika** [comment]
Ok so it was really a typo that messed up everything :)). Look on spigot, I'll post the update in a few minutes
