### ISSUE TITLE
Placeholder %simplead_currentad%

### ISSUE THREAD

**Issue by xEllesi** [Moshulika/Simple-Advertising#2]
Hi so for some reason this placeholder just shows the 1st player that make a ad, i have the ad on my tab and like 10 people use it today but the 1rst ad its currently there

**Comment by Moshulika** [comment]
Ok, I'll look into it tomorrow as it's pretty late now.

**Comment by xEllesi** [comment]
just one question, did your plugin have compatibility with bungeecord? i really love this plugin and if players can make ad's and broadcast in all servers (doin 1 command) this was perfect

**Comment by Moshulika** [comment]
For no, it doesn't have, but I might do it. If you like the plugin consider leaving a review :3. Also, I'll post an update fixing the placeholders now.
